[llm] # llm config
name = "groq:gemma2-9b-it"
base_url = ""
api_key = ""
max_tokens = 1024
temperature = 0.0
prompt= '''
You are an AI agent equipped with SQLite tools. Your goal is to help users interact with SQLite database. You use the
right tools to get the final results.
'''

[embedder] # Text embedding Model config
model = "sentence-transformers/all-MiniLM-L6-v2"
token = ""
normalize = true

[chunker] # chunker config
chunk_strategy = "table_level" # "table_level" or "field_level"

[retriever] # retriever config
top_k = 10

[reranker] # Text re-ranking Model config
model = "BAAI/bge-reranker-base"
token = ""
top_k = 4

[file_paths] # Data files names and paths config
src_dir = "C:/Users/pc/Documents/genai-training-pydanticai/data/db_explorer"
db_file = "db/chinook.sqlite"
kb_dir = "kb"
vector_db_dir = "vector_db"
eval_file = "eval/chinook_eval.json"
eval_file_with_response = "eval/chinook_eval_with_response.json"
results_dir = "results"

[logfire] # log fire config
token = ""
 
[judge_llm] # Evaluator/Judge LLM config
name = "gemma2-9b-it"
base_url = ""
api_key = ""
max_tokens = 1024
temperature = 0.0
prompt = ""
  

