from dataclasses import dataclass
from pydantic_ai import Agent, RunContext
import logfire
from llm import *
from langchain_community.vectorstores import FAISS
import sqlite3
from config_reader import *


@dataclass
class Deps:
    vector_db: FAISS
    retriever_top_k: int
    db_file_path: str


def get_table_info(ctx: RunContext[Deps], user_query: str) -> str:
    """Get the information of all the tables

    Args:
        ctx: The context.
        user_query: The user query.
    """
    logfire.info(f"query selected by model:{user_query}")
    base_retriever = ctx.deps.vector_db.as_retriever(
        search_kwargs={"k": ctx.deps.retriever_top_k}
    )
    results = base_retriever.invoke(user_query)
    results_str = "\n".join([result.page_content for result in results])
    print(results_str)
    return results_str


def run_sql_tool(ctx: RunContext[Deps], sql_query: str) -> list[tuple]:
    """Run sql query on the database

    Args:
        ctx: The context.
        sql_query: The generated sql query.
    """
    logfire.info(f"sql query generated by model:{sql_query}")
    try:
        with sqlite3.connect(ctx.deps.db_file_path) as conn:
            cursor = conn.cursor()
            cursor.execute(sql_query)
            results = cursor.fetchall()
            return results
    except Exception as e:
        print(e)
    return []


def create_sql_agent():
    sql_agent = Agent(
        model=build_model(),
        system_prompt=settings.llm.prompt,
        deps_type=Deps,
        tools=[get_table_info, run_sql_tool],
        retries=3,
    )
    return sql_agent


""" 
Sample queries
[
    {
        "question": "How many albums are there?",
        "answer": "347",
    },
    {
        "question": "How many distinct genres are there?",
        "answer": "25",
    },
    {
        "question": "Which Employee has the Highest Total Number of Customers?",
        "answer": "Peacock Jane has the most customers (she has 21 customers)",
    },
    {
        "question": "Who are our top Customers according to Invoices?",
        "answer": "Helena Holy, Richard Cunningham, Luis Rojas, Ladislav Kovacs, and Hugh O\u2019Reilly are the top five customers who have spent the highest amount of money according to the invoice",
    },
    {
        "question": "How many Rock music listeners are there?",
        "answer": "We found out that all 59 customers in the database have listened to Rock Music.",
    },
    {
        "question": "What artists have written most rock music songs?",
        "answer": "Led Zeppelin tops the list of Artists who have written the most Rock Music with 114 songs followed Closely by U2 with 112 music.",
    },
    {
        "question": "Which artist has earned the most according to the Invoice Lines? How much is it?",
        "answer": "The Artist who has earned the most according to the invoice lines is Iron Maiden with a total of $138.6.",
    },
    {
        "question": "How many tracks have a song length greater than the average song length?",
        "answer": "Out of 3503 songs in the database, we found out that 494 of these songs have length more than the average music length of 393,599.21 milliseconds.",
    },
    {
        "question": "What is the most popular genre for Australia?",
        "answer": "Rock is the most popular song for Australia",
    },
] """
