[llm] # llm config
name = "groq:llama-3.3-70b-versatile"
base_url = ""
api_key = ""
max_tokens = 2048
temperature = 0.0
prompt= '''
You are an AI assistant to classify a customer support ticket into one of the following categories:
<categories> 
    <category> 
        <label>Billing Inquiries</label>
        <content> Questions about invoices, charges, fees, and premiums Requests for clarification on billing statements Inquiries about payment methods and due dates 
        </content> 
    </category> 
    <category> 
        <label>Policy Administration</label>
        <content> Requests for policy changes, updates, or cancellations Questions about policy renewals and reinstatements Inquiries about adding or removing coverage options 
        </content> 
    </category> 
    <category> 
        <label>Claims Assistance</label> 
        <content> Questions about the claims process and filing procedures Requests for help with submitting claim documentation Inquiries about claim status and payout timelines 
        </content> 
    </category> 
    <category> 
        <label>Coverage Explanations</label> 
        <content> Questions about what is covered under specific policy types Requests for clarification on coverage limits and exclusions Inquiries about deductibles and out-of-pocket expenses 
        </content> 
    </category> 
    <category> 
        <label>Quotes and Proposals</label> 
        <content> Requests for new policy quotes and price comparisons Questions about available discounts and bundling options Inquiries about switching from another insurer 
        </content> 
    </category> 
    <category> 
        <label>Account Management</label> 
        <content> Requests for login credentials or password resets Questions about online account features and functionality Inquiries about updating contact or personal information 
        </content> 
    </category> 
    <category> 
        <label>Billing Disputes</label> 
        <content> Complaints about unexpected or incorrect charges Requests for refunds or premium adjustments Inquiries about late fees or collection notices 
        </content> 
    </category> 
    <category> 
        <label>Claims Disputes</label> 
        <content> Complaints about denied or underpaid claims Requests for reconsideration of claim decisions Inquiries about appealing a claim outcome 
        </content> 
    </category> 
    <category> 
        <label>Policy Comparisons</label> 
        <content> Questions about the differences between policy options Requests for help deciding between coverage levels Inquiries about how policies compare to competitors' offerings 
        </content> 
    </category> 
    <category> 
        <label>General Inquiries</label> 
        <content> Questions about company contact information or hours of operation Requests for general information about products or services Inquiries that don't fit neatly into other categories 
        </content> 
    </category>
</categories>

Respond with just the label of the category.
'''

[embedder] # Text embedding Model config
model = "sentence-transformers/all-MiniLM-L6-v2"
token = ""
normalize = true

[retriever] # retriever config
top_k = 5

[file_paths] # Data files names and paths config
src_dir = "C:/Users/pc/Documents/genai-training-pydanticai/data/text_classifier"
kb_dir = "kb"
vector_db_dir = "vector_db"
eval_file = "eval/ticket_eval.json"
eval_file_with_response = "eval/ticket_eval_with_response_llm_prompt3.json"
results_dir = "results"
results_report_file="report_llm_rag.csv"
results_matrix_file="cm_llm_rag.png"

[logfire] # log fire config
token = ""